site_name: knowledge-base
theme:
    name: material
    features:
      - navigation.footer
      - navigation.top
      - content.code.copy
    palette:
      # Palette toggle for light mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
      # Palette toggle for dark mode
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - glightbox
  - pdf-export
  - search:
      lang:
        - de
        - en
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - i18n:
      default_language: de
      material_alternate: true
      languages:
        en:
          name: Englisch
          build: true
          link: /en/
        de:
          name: Deutsch
          build: true
          link: /knowledge-base/de/
      nav_translations:
        de:
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Maggomann
    - icon: fontawesome/brands/github
      link: https://github.com/Maggoman
